/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/syNByGAMhWP
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"
import TimeComponent from "./TimeComponent";

export function Timezones() {
  return (
    (<div className="max-w-6xl mx-auto p-4 sm:p-6 md:p-8">
      <h1 className="text-2xl font-bold mb-6">World Clock</h1>
      <div
        className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <TimeComponent IANA="America/La_Paz" city="Bolivia"/> 
        <TimeComponent IANA="America/Costa_Rica" city="Costa Rica"/> 
        <TimeComponent IANA="America/Santo_Domingo" city="Republica Dominicana"/>  
        <Card className="bg-[#FF6B6B] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">12:34</div>
            <div className="text-sm mt-2">New York, USA</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#FFA500] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">18:34</div>
            <div className="text-sm mt-2">London, UK</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#9B59B6] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">01:34</div>
            <div className="text-sm mt-2">Tokyo, Japan</div>
            <div className="text-sm mt-1">June 9, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#2980B9] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">03:34</div>
            <div className="text-sm mt-2">Sydney, Australia</div>
            <div className="text-sm mt-1">June 9, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#27AE60] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">08:34</div>
            <div className="text-sm mt-2">Dubai, UAE</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#E74C3C] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">15:34</div>
            <div className="text-sm mt-2">Berlin, Germany</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#8E44AD] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">23:34</div>
            <div className="text-sm mt-2">Moscow, Russia</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#16A085] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">04:34</div>
            <div className="text-sm mt-2">Cape Town, South Africa</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#F1C40F] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">09:34</div>
            <div className="text-sm mt-2">Bangkok, Thailand</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#D35400] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">20:34</div>
            <div className="text-sm mt-2">Rio de Janeiro, Brazil</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#7F8C8D] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">06:34</div>
            <div className="text-sm mt-2">Nairobi, Kenya</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
        <Card className="bg-[#C0392B] text-white">
          <CardContent className="p-6 flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">11:34</div>
            <div className="text-sm mt-2">Mexico City, Mexico</div>
            <div className="text-sm mt-1">June 8, 2024</div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}
